### ISSUE TITLE
can the 403 forbidden error not have stack trace

### ISSUE THREAD

**Issue by mkanoor** [RedHatInsights/catalog-ui#189]
![Screen Shot 2019-04-30 at 11 27 24 AM](https://user-images.githubusercontent.com/6452699/56973568-1620c680-6b3b-11e9-98f3-a1ab4d3ccea4.png)

**Comment by mkanoor** [comment]
I am seeing this in CI not sure in production if it hides the stack trace

**Comment by mkanoor** [comment]
Multiple 403 error messages pop up when a non admin user goes into Settings -> User Access Management

![Screen Shot 2019-05-01 at 5 52 50 PM](https://user-images.githubusercontent.com/6452699/57044979-40a57900-6c3a-11e9-93f4-117465ac9596.png)

**Comment by gmcculloug** [comment]
Should be resolved by https://github.com/RedHatInsights/insights-rbac-ui/pull/19

**Comment by gmcculloug** [comment]
@mkanoor Please validate and test if this  issue has been resolved.
